#!/usr/bin/env bash
# Linux/macOS CI/local: same behavior as Export-OpenScadStl.ps1
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODEL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
if [[ -n "${1:-}" ]]; then
  if [[ "$1" = /* ]] || [[ "$1" =~ ^[A-Za-z]:[\\/] ]]; then
    CONFIG="$1"
  else
    CONFIG="$MODEL_DIR/$1"
  fi
else
  CONFIG="${KBCF_STAMP_CONFIG:-$MODEL_DIR/stamp-config.json}"
fi
if [[ "$CONFIG" != /* ]] && [[ ! "$CONFIG" =~ ^[A-Za-z]:[\\/] ]]; then
  CONFIG="$MODEL_DIR/$CONFIG"
fi
if [[ ! -f "$CONFIG" ]]; then
  echo "Config not found: $CONFIG" >&2
  exit 1
fi
CONFIG_REL="${CONFIG#$MODEL_DIR/}"
if [[ "$CONFIG_REL" == "$CONFIG" ]]; then
  CONFIG_REL="$(basename "$CONFIG")"
fi

escape_scad() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

stem_from_scad() {
  local base
  base="$(basename "$1" .scad)"
  echo "${base//-/_}"
}

cd "$MODEL_DIR"
PREVIEW="$(jq -r '.preview // true' "$CONFIG")"
# Local / CI prototype: low $fn (preview=true). Production (KBCF_PRODUCTION=1): preview=false, $fn=128 in config.scad.
if [[ "${KBCF_PRODUCTION:-}" == "1" ]]; then
  SCAD_PREVIEW="false"
else
  SCAD_PREVIEW="$PREVIEW"
fi

BRAND="$(jq -r '.brand_name' "$CONFIG")"
PROD="$(jq -r '.product_name' "$CONFIG")"
VER="$(jq -r '.product_version' "$CONFIG" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

# Output folder: latest-builds/<version> for production (KBCF_PRODUCTION=1), else .../<version>-prototype.
if [[ "${KBCF_PRODUCTION:-}" == "1" ]]; then
  VERSION_FOLDER="$VER"
else
  VERSION_FOLDER="${VER}-prototype"
fi
SHOW_VER_LINE="$(jq -r '.stamp_show_version_line // true' "$CONFIG")"
if [[ "$SHOW_VER_LINE" == "true" ]]; then
  if [[ "${KBCF_PRODUCTION:-}" == "1" ]]; then
    LINE3="$VER"
  else
    LINE3="$VER"
    if [[ "$PREVIEW" == "true" ]]; then
      LINE3="$VER Prototype"
    fi
  fi
else
  LINE3="$(jq -r '.stamp_line3 // empty' "$CONFIG")"
fi
LINE3="$(echo "$LINE3" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
LINE4="$(jq -r '.stamp_line4 // empty' "$CONFIG")"
LINE4="$(echo "$LINE4" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

STAMP_FILE="$MODEL_DIR/stamp-generated.scad"
{
  echo "// AUTO-GENERATED by scripts/export-open-scad-stl.sh - do not edit by hand"
  echo "// Source: $CONFIG_REL"
  echo ""
  printf 'info_stamp_line1 = "%s";\n' "$(escape_scad "$BRAND")"
  printf 'info_stamp_line2 = "%s";\n' "$(escape_scad "$PROD")"
  printf 'info_stamp_line3 = "%s";\n' "$(escape_scad "$LINE3")"
  printf 'info_stamp_line4 = "%s";\n' "$(escape_scad "$LINE4")"
  while IFS= read -r row; do
    scad="$(echo "$row" | jq -r '.scad')"
    face="$(echo "$row" | jq -r '.stamp.face // empty')"
    st="$(stem_from_scad "$scad")"
    if [[ "$face" == "bottom" ]]; then
      echo "${st}_stamp_bottom = true;"
      echo "${st}_stamp_top = false;"
    elif [[ "$face" == "top" ]]; then
      echo "${st}_stamp_bottom = false;"
      echo "${st}_stamp_top = true;"
    else
      echo "${st}_stamp_bottom = false;"
      echo "${st}_stamp_top = false;"
    fi
  done < <(jq -c '.exports[]' "$CONFIG")
} > "$STAMP_FILE"
echo "Wrote $STAMP_FILE"

if ! command -v openscad >/dev/null 2>&1; then
  echo "openscad not in PATH; install OpenSCAD to export STLs." >&2
  exit 1
fi

EXPORT_DEFS=(-D "mesh_preview=false" -D "crosssection_view=false" -D "preview=$SCAD_PREVIEW")

while IFS= read -r row; do
  scad="$(echo "$row" | jq -r '.scad')"
  stl_raw="$(echo "$row" | jq -r '.stl')"
  stl="${stl_raw//\{version_folder\}/$VERSION_FOLDER}"
  stl="${stl//\{product_version\}/$VERSION_FOLDER}"
  out_path="$MODEL_DIR/$stl"
  mkdir -p "$(dirname "$out_path")"
  echo "Export $scad -> $stl"
  openscad "${EXPORT_DEFS[@]}" -o "$out_path" "$MODEL_DIR/$scad"
done < <(jq -c '.exports[]' "$CONFIG")

echo "Done."
