<#
.SYNOPSIS
  Regenerates stamp-generated.scad from stamp-config.json and exports STLs via OpenSCAD.
#>
param(
    [string]$ConfigPath = ""
)

$ErrorActionPreference = "Stop"
$ModelDir = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
if ([string]::IsNullOrWhiteSpace($ConfigPath)) {
    $ConfigPath = Join-Path $ModelDir "stamp-config.json"
}
$ConfigPath = (Resolve-Path -LiteralPath $ConfigPath).Path
$root = $ModelDir.TrimEnd('\', '/')
$cfgNorm = $ConfigPath
$sep = [string][IO.Path]::DirectorySeparatorChar
if ($cfgNorm.StartsWith($root + $sep, [StringComparison]::OrdinalIgnoreCase)) {
    $configRel = $cfgNorm.Substring($root.Length + 1)
} elseif ($cfgNorm.Equals($root, [StringComparison]::OrdinalIgnoreCase)) {
    $configRel = [IO.Path]::GetFileName($ConfigPath)
} else {
    $configRel = [IO.Path]::GetFileName($ConfigPath)
}

$cfg = Get-Content -LiteralPath $ConfigPath -Raw -Encoding UTF8 | ConvertFrom-Json

function Escape-ScadString([string]$s) {
    if ($null -eq $s) { return "" }
    $s = $s.Replace('\', '\\')
    return $s.Replace('"', '\"')
}

function Get-ScadStem([string]$relativeScadPath) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($relativeScadPath)
    return ($name -replace '-', '_')
}

$line1 = [string]$cfg.brand_name
$line2 = [string]$cfg.product_name
$verTag = [string]$cfg.product_version.Trim()
$isProduction = ($env:KBCF_PRODUCTION -eq "1")
$showVerLine = $true
if ($null -ne $cfg.stamp_show_version_line) { $showVerLine = [bool]$cfg.stamp_show_version_line }
if ($showVerLine) {
    if ($isProduction) {
        $line3 = $verTag
    } elseif ($cfg.preview -eq $true) {
        $line3 = ("{0} Prototype" -f $verTag).Trim()
    } else {
        $line3 = $verTag
    }
} else {
    $line3 = ""
    if ($null -ne $cfg.stamp_line3) { $line3 = [string]$cfg.stamp_line3 }
}

$line4 = ""
if ($null -ne $cfg.stamp_line4) { $line4 = [string]$cfg.stamp_line4 }

$stampPath = Join-Path $ModelDir "stamp-generated.scad"
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by scripts/Export-OpenScadStl.ps1 - do not edit by hand")
[void]$sb.AppendLine("// Source: $configRel")
[void]$sb.AppendLine("")
[void]$sb.AppendLine(('info_stamp_line1 = "{0}";' -f (Escape-ScadString $line1)))
[void]$sb.AppendLine(('info_stamp_line2 = "{0}";' -f (Escape-ScadString $line2)))
[void]$sb.AppendLine(('info_stamp_line3 = "{0}";' -f (Escape-ScadString $line3)))
[void]$sb.AppendLine(('info_stamp_line4 = "{0}";' -f (Escape-ScadString $line4)))

$exports = @($cfg.exports)
foreach ($exp in $exports) {
    $stem = Get-ScadStem $exp.scad
    $face = $null
    if ($null -ne $exp.stamp) { $face = [string]$exp.stamp.face }
    $bottom = $false
    $top = $false
    if ($face -eq "bottom") { $bottom = $true }
    elseif ($face -eq "top") { $top = $true }
    [void]$sb.AppendLine(('{0}_stamp_bottom = {1};' -f $stem, ($(if ($bottom) { "true" } else { "false" }))))
    [void]$sb.AppendLine(('{0}_stamp_top = {1};' -f $stem, ($(if ($top) { "true" } else { "false" }))))
}

[System.IO.File]::WriteAllText($stampPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $stampPath"

function Find-OpenScad {
    $pf86 = [Environment]::GetEnvironmentVariable("ProgramFiles(x86)")
    foreach ($c in @(
            $env:OPENSCAD_PATH,
            "${env:ProgramFiles}\OpenSCAD\openscad.com",
            "${env:ProgramFiles}\OpenSCAD\openscad.exe",
            $(if ($pf86) { Join-Path $pf86 "OpenSCAD\openscad.com" })
        )) {
        if ($c -and (Test-Path -LiteralPath $c)) { return $c }
    }
    $cmd = Get-Command openscad -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Path }
    return $null
}

$openscad = Find-OpenScad
if (-not $openscad) {
    throw "OpenSCAD not found. Set OPENSCAD_PATH or install OpenSCAD."
}

# Match export-open-scad-stl.sh: production forces preview=false ($fn=128); local uses stamp-config preview (default true, $fn=32).
$scadPreview = if ($isProduction) {
    "false"
} elseif (($null -eq $cfg.preview) -or ($cfg.preview -eq $true)) {
    "true"
} else {
    "false"
}
$exportDefines = @("-D", "mesh_preview=false", "-D", "crosssection_view=false", "-D", "preview=$scadPreview")
$versionFolder = if ($isProduction) { $verTag } else { "{0}-prototype" -f $verTag }

foreach ($exp in $exports) {
    $in = Join-Path $ModelDir $exp.scad
    $relStl = [string]$exp.stl -replace '\{version_folder\}', $versionFolder
    $relStl = $relStl -replace '\{product_version\}', $versionFolder
    $relStl = $relStl -replace '/', [IO.Path]::DirectorySeparatorChar
    $out = [IO.Path]::GetFullPath([IO.Path]::Combine($ModelDir, $relStl))
    $outDir = Split-Path -Parent $out
    if (-not (Test-Path -LiteralPath $outDir)) {
        New-Item -ItemType Directory -Path $outDir -Force | Out-Null
    }
    Write-Host "Export $($exp.scad) -> $relStl"
    & $openscad @exportDefines -o $out $in
    if ($LASTEXITCODE -ne 0) {
        throw "OpenSCAD failed for $($exp.scad) (exit $LASTEXITCODE)"
    }
}

Write-Host "Done."
