services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-db/data:/data/db

  api:
    build:
      context: .
      dockerfile: tektonology-api/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - .env.local
    environment:
      - MONGODB_URI=mongodb://mongo:27017/tektonology
      - API_PORT=3001
    command: npx -y nodemon --watch /app/tektonology-api --watch /app/services/shared --legacy-watch --polling-interval 1000 index.js
    volumes:
      - ./tektonology-api:/app/tektonology-api
      - ./services/shared:/app/services/shared

volumes:
  redis-data:
