// AUTO-GENERATED by scripts/export-open-scad-stl.sh - do not edit by hand
// Source: stamp-config.json

info_stamp_line1 = "Tektonology";
info_stamp_line2 = "";
info_stamp_line3 = "Prayer Sole v3.8.3";
info_stamp_line4 = "Psalm 145:14";
tread_stamp_bottom = false;
tread_stamp_top = true;
collar_stamp_bottom = false;
collar_stamp_top = false;
cap_stamp_bottom = false;
cap_stamp_top = false;
