// AUTO-GENERATED by scripts/Export-OpenScadStl.ps1 - do not edit by hand
// Source: stamp-config.json

info_stamp_line1 = "Tektonology";
info_stamp_line2 = "Prayer Sole v3.8.1";
info_stamp_line3 = "Psalm 145:14";
info_stamp_line4 = "";
tread_stamp_bottom = false;
tread_stamp_top = true;
collar_stamp_bottom = false;
collar_stamp_top = false;
cap_stamp_bottom = false;
cap_stamp_top = false;
