// AUTO-GENERATED by scripts/Export-OpenScadStl.ps1 - do not edit by hand
// Source: print-stamp-config.json

info_stamp_line1 = "Tektonology";
info_stamp_line2 = "";
info_stamp_line3 = "Foundation v3.8.1";
info_stamp_line4 = "Psalm 145:14";
kneeler_boot_insert_stamp_bottom = false;
kneeler_boot_insert_stamp_top = true;
kneeler_boot_slipper_stamp_bottom = false;
kneeler_boot_slipper_stamp_top = false;
kneeler_boot_cap_stamp_bottom = false;
kneeler_boot_cap_stamp_top = false;
